jq_fadeIn_or_out_list_in_circle
lord-sumit/central_repo pull request #22
Opened 2017-09-10 15:52 UTC by lord-sumit

2017-09-11 09:54 UTC, rajatbansal93 requested changes

2017-09-11 09:54 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +  var slideshow = new SlideShow($("body"), $("#slideshow"), $("#myList"));
Why you need to select and pass body?

2017-09-11 09:54 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +  this.$body = body;
Body of document is always constant.
you don't need to store it.

2017-09-11 09:54 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +  this.$list = list.children();
If it storing children of list then why it's name is list?

2017-09-11 09:55 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +$(document).ready(function(){
spacing issue

2017-09-11 09:56 UTC, rajatbansal93 requested changes

2017-09-11 09:56 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +SlideShow.prototype.fadeInOutElement = function(first_argument) {
first_argument?

and in second cycle also it's first_argument?

2017-09-11 09:56 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +    if($(this).text() == _this.$list.last().text()){
lot of redundacny

2017-09-11 09:58 UTC, rajatbansal93 requested changes

2017-09-11 09:58 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +      $(this).next().fadeToggle(300,_this.fadeInOutElement());
spacing issues

2017-09-11 09:58 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +      _this.$list.first().fadeToggle(300,_this.fadeInOutElement());
spacing issue

2017-09-11 09:58 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +    else{
spacing issue

2017-09-11 09:59 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +  this.$list.first().fadeToggle(300,this.fadeInOutElement());
300 should go in a constant in prototype

2017-09-13 08:02 UTC, rajatbansal93 requested changes

2017-09-13 08:02 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +function SlideShow(slideShow, list) {
why not starting with $

2017-09-13 08:02 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +SlideShow.prototype.during = 300;
Constant start with capital letter, it should be During

2017-09-13 08:02 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +  this.insertElement($("body"), this.$slideShowElement);
why are you doing things other than binding events in this function?

2017-09-13 08:02 UTC, rajatbansal93 commented on jquery/exercise8/js/slideshow.js
> +SlideShow.prototype.fadeInOutElement = function() {
take out seperate methods for fad in and out

2017-10-15 07:27 UTC, lord-sumit commented on jquery/exercise8/js/slideshow.js
> +SlideShow.prototype.fadeInOutElement = function() {
brother i use toggle method for fade in and out due to which i cann't break it

2017-10-15 07:28 UTC, closed without merging